CREATE TABLE tb_racas (
    id SERIAL PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tb_pets (
    id SERIAL PRIMARY KEY,
    id_cliente BIGINT UNSIGNED REFERENCES tb_clientes(id) ON DELETE CASCADE,
    id_raca BIGINT UNSIGNED REFERENCES tb_racas(id) ON DELETE SET NULL,
    nome VARCHAR(100) NOT NULL,
    data_nascimento DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);